# Generated by Django 2.2.3 on 2020-11-11 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_demomodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='demoModel',
        ),
    ]
